### ISSUE TITLE
Pokemon Sword DLC doesn't match

### ISSUE THREAD

**Issue by Chibifreak** [sudachi-emu/sudachi#113]
Pokemon Sword and Shield 1.3.2 + expansion pass dlc doesn't match. 
I have tried with Suyu and Yuzu also, and both of them also same notification the dlc doesn't match. Strangely Yuzu still can load the dlc and run well in-game but for Suyu and Sudaichi cannot.

**Comment by ManuelJimena** [comment]
The DLC problem occurs from the implementation of the Home menu, both here and in Suyu.
If you want to use Sudachi without this problem, use version v7715077

**Comment by Chibifreak** [comment]
v7715077 is working normally.. 👍
