### ISSUE TITLE
Softlock on Paper Mario: The Thousand-Year Door

### ISSUE THREAD

**Issue by teogorghin** [sudachi-emu/sudachi#169]
Infinite loading on the loading screen, when entering in the room where the sixth crystal star is located (Poshley Heights, that room with ghosts).
Issue occurs both on OpenGL and Vulkan, on v1.0.2.
I checked the logs and I didn't saw any error.

Device which occurs that issue:
Intel i5-1135G7 Laptop with 8GB RAM.
Operating system: Ubuntu 22.04, with latest Mesa drivers
`client glx vendor string: Mesa Project and SGI
    Device: Mesa Intel(R) Xe Graphics (TGL GT2) (0x9a49)
OpenGL renderer string: Mesa Intel(R) Xe Graphics (TGL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.0.8 - kisak-mesa PPA
OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.8 - kisak-mesa PPA
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.0.8 - kisak-mesa PPA`

**Comment by ffrasisti** [comment]
I think this is also happening in ryujinx
