### ISSUE TITLE
Cubeb commit[7d6c2f] not found

### ISSUE THREAD

**Issue by ImpXada** [sudachi-emu/sudachi#35]
When I tried to automatically build the Android version of Sudachi, I encountered this error message: "fatal: remote error: upload-pack: not our ref 7d6c2fdb7981d0dfe8b68748ed1b1c8b1c67aa9e fatal: Fetched in submodule path 'externals/cubeb', but it did not contain 7d6c2fdb7981d0dfe8b68748ed1b1c8b1c67aa9e. Direct fetching of that commit failed." When I attempted to switch to this branch of cubeb locally, I faced the same issue. Should I consider upgrading cubeb's dependencies?

**Comment by Dragonborn1117** [comment]
Running this command plz and it may solves the problem.
git submodule update --force --recursive --init --remote

**Comment by jason5545** [comment]
The latest commit should fix it.
