### ISSUE TITLE
having issues building sudachi

### ISSUE THREAD

**Issue by jvhellraiser** [sudachi-emu/sudachi#44]
I get this error using terminal, using cmake it completes the task but when building with visual studio 2022 it ends with errors too any help?

-- Target architecture: x86_64
-- Found Boost: C:/Users/javie/Desktop/suyu/sudachi/sudachi/vcpkg_installed/x64-windows/include (found suitable version "1.83.0", minimum required is "1.57")
-- Could NOT find mcl (missing: mcl_DIR)
-- Could NOT find tsl-robin-map (missing: tsl-robin-map_DIR)
-- Could NOT find xbyak (missing: xbyak_DIR)
-- Could NOT find Zydis (missing: Zydis_DIR)
CMake Error at externals/dynarmic/externals/mcl/CMakeLists.txt:35 (message):
  In-source builds are not allowed.

CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/CMakePackageConfigHelpers.cmake:467 (configure_file):
  configure_file attempted to configure a file:
  C:/Users/javie/Desktop/suyu/sudachi/sudachi/externals/dynarmic/externals/mcl/mclConfig.cmake
  into a source directory.
Call Stack (most recent call first):
  externals/dynarmic/externals/mcl/CMakeLists.txt:121 (configure_package_config_file)

-- Configuring incomplete, errors occurred!

C:\Users\javie\Desktop\suyu\sudachi\sudachi>

"and how do you pull updates? cause git pull is not helping..."
![Screenshot 2024-04-08 224330](https://github.com/sudachi-emu/sudachi/assets/16488761/0b02c441-d2da-4ad3-8363-11649cd1e7f8)

from the terminal
![Screenshot 2024-04-08 225426](https://github.com/sudachi-emu/sudachi/assets/16488761/d5a8d4fd-087d-4848-a537-4e72148a5cf5)

**Comment by jarrodnorwell** [comment]
`points` is available in Qt6 (unsure which it first appeared), I'll need to add a Qt version to bring back Qt5 support or state that Sudachi now requires Qt6 (I'm using v6.7.0)
