### ISSUE TITLE
is edd7896-windows.7z virus or just a fasle positive by windows?!

### ISSUE THREAD

**Issue by Xmanant03real** [sudachi-emu/sudachi#59]
![Screenshot 2024-04-11 183003](https://github.com/sudachi-emu/sudachi/assets/166774105/c73ac43d-0434-4d76-9d56-f4b672fb6241)

hi i was wondering if this latest download of edd7896-windows.7z is actually suspicious or if its a false positive that windows is thinking is malware? I downloaded the latest one and as soon as i downloaded is windows popped up with 1 virus found but was quickly trashed by windows defender. i got worried for a few mins but later realized this had to be a false positive by windows due to being a brand new version of the software. nothing bad happened with my system which mi glad about i was just curious if this was a true false positive? i appreciate this be known in case not sure if its real or if its false positive by windows.  just curious. thanks here's  a screenshot when it happened in case.

**Comment by jarrodnorwell** [comment]
False positive, emulators often get flagged but there's nothing malicious going on

**Comment by Xmanant03real** [comment]
Awesome! i appreciate the help!
